---
title: "Passive Acoustic Monitoring Slow Moving Platform Comparison Study"
subtitle: "Drifting Acoustic Recording Buoys vs. PAM Equipped Seagliders"
page-layout: full
---

# Project Overview

This project will aim to to assess the performance of two slow moving, passive acoustic recording platforms. Several factors will be considered in this comparison study including the platform's ability to detect low frequency baleen whale calls, overall operational metrics, and ... Blue and fin whale calls collected from drifting acoustic buoys deployed during the 2024 California Current Cetacean and Ecosystem Assessment Cruise (CalCurCEAS) and a concurrent glider survey will be used in this assessment. This study will use the Low Frequency Detection and Classification System (cite Mark) to detect and classify baleen whale calls.

# Outline/To-Do

-   Test LFDCS on ADRIFT data where blue/fin presence is known and compare results
    -   if it performs well, test it on glider data with known blue/fin presence
    -   if it performs poorly, use manual detection methods for calls
-   Assess drifter and glider acoustics, operational, and resource metrics
    -   deployment capacity, expenses, personnel needs,
    -   More examples from Shannon for glider rodeo - [Operational](https://docs.google.com/spreadsheets/d/10TMGwo6BfDa2tdHZmhrUEvi53b_sBSuNzNJUJwzWmg0/edit?usp=sharing), [Bioacoustics](https://docs.google.com/spreadsheets/d/1zmvolE6VS1vwD-7DGvL6mt86yRvGQEYWTR5Hc32g-ic/edit?usp=sharing), [responses from experience users](https://docs.google.com/spreadsheets/d/1n06wtObvEDB6NDfGVXgmKRvRJhPu5n_5VBh86UvXNn0/edit?usp=sharing)
-   Build out Zotero library with other platform comparison studies
    -   what do other people use to assess performance
    -   
-   
