---
title: New Content
editor: 
  markdown: 
    wrap: 72
bibliography: references.yaml
---

## Process

-   identify drifts with high percentage of blue and fin detections to
    test lfdcs on

    -   ADRIFT_098 has

-   compare LFDCS results to manual annotation

-   do the same for glider deployment

## ADRIFT Summary

```{r}
df <- readRDS("../_data/ADRIFT/bm_bp_presence_summary.rds")
df
```

## Initial LFDCS Results

The narrow band Southern California call library that is currently used
on buoys in the Santa Barbara Channel was used on several ADRIFT
datasets that have been manually scanned for blues and fins and one
ADRIFT dataset that had an AI model applied to it (see [Fin Whale AI in
ADRIFT report](https://sael-swfsc.github.io/Adrift/content/finAI.html)).

### ADRIFT 98

This drift was chosen because it had the highest percentage of presence
hours for blue and fin whales out of the ADRIFT dataset (see ADRIFT
Summary above)

### ADRIFT 71

This drift was chosen because it had no fin or blue whale manual
detections (assessing false positive rate)
