on:
  push:
    branches: main

name: Render and Publish

jobs:
  build-deploy:
    runs-on: macos-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2 

      - name: Set up R (needed for Rmd)
        uses: r-lib/actions/setup-r@v2

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libfreetype6-dev libfontconfig1-dev pkg-config

      - name: Install R packages (for rendering .qmd)
        run: |
          Rscript -e 'install.packages(c("rmarkdown", "knitr", "jsonlite", "kableExtra", "dplyr"))'

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          # To install LaTeX to build PDF book 
          tinytex: false
          # uncomment below and fill to pin a version
          # version: 0.9.600
        # env:
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions

      
      # add software dependencies here

      - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions
